name: ci-cd

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
env:
  ECS_CLUSTER: ${{ vars.ECS_CLUSTER }}         
  ECS_SERVICE: ${{ vars.ECS_SERVICE }}         
  CONTAINER_NAME: notesy                       
  APP_NAME: ${{ vars.APP_NAME }}
  JAVA_VERSION: "25"
  JFROG_URL: ${{ vars.JFROG_URL }}
  JFROG_REPO: ${{ vars.JFROG_REPO }}
  SONAR_HOST_URL: ${{ secrets.SONAR_TOKEN }}
  SONAR_ORGANIZATION: ${{ vars.SONAR_ORGANIZATION  }}
  SONAR_PROJECT_KEY: ${{ vars.SONAR_PROJECT_KEY }}

  VAULT_ADDR: ${{vars.VAULT_ADDR}}
  VAULT_SECRET_ID: ${{secrets.VAULT_AUTH_PATH}}
  VAULT_ROLE: ${{secrets.VAULT_ROLE}}
  VAULT_JFROG_SECRET_PATH: ${{vars.VAULT_JFROG_SECRET_PATH}}

jobs:
  gitleaks:
    name: Gitleaks Secret Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_ENABLE_COMMENTS: "false"


  trivy-fs:
    name: Trivy Dependency & Config Scan
    needs: gitleaks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy filesystem scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: fs
          scan-ref: .
          scanners: vuln,misconfig
          severity: CRITICAL,HIGH
          ignore-unfixed: true
          exit-code: "0"